name: CSV data
language: python
variables:
  - name: Topic
    inputType: OutputTopic
    description: Name of the output topic to write into
    defaultValue: csv-data
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
