name: Streamlit
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: streamlit_file.py
