name: KeywordCount
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: csv-data
    required: false
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: counts
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
