name: Redis
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic
    defaultValue: transform
    required: true
  - name: redis_host
    inputType: FreeText
    description: Host address for the Redis instance
    defaultValue: redis-14169.c72.eu-west-1-2.ec2.cloud.redislabs.com
    required: true
  - name: redis_port
    inputType: FreeText
    description: Port for the Redis instance
    defaultValue: 14169
    required: true
  - name: redis_password
    inputType: FreeText
    description: Password for the Redis instance
    defaultValue: FPTZKKjuWHdmVLkBKXcmFj7jYg08OHz8
    required: false
  - name: redis_username
    inputType: FreeText
    description: Username for the Redis instance
    defaultValue: default
    required: false
  - name: storage_key
    inputType: FreeText
    description: ''
    defaultValue: 1min
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
